name: HCMT
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.08.22=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.10=h7f8727e_2
  - pip=23.2.1=py39h06a4308_0
  - python=3.9.18=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2023c=h04d1e81_0
  - wheel=0.38.4=py39h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - absl-py==2.0.0
    - astunparse==1.6.3
    - cachetools==5.3.1
    - certifi==2023.7.22
    - charset-normalizer==3.2.0
    - dm-sonnet==2.0.1
    - dm-tree==0.1.8
    - flatbuffers==23.5.26
    - gast==0.5.4
    - google-auth==2.23.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.58.0
    - h5py==3.9.0
    - idna==3.4
    - importlib-metadata==6.8.0
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - libclang==16.0.6
    - markdown==3.4.4
    - markupsafe==2.1.3
    - numpy==1.26.0
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - protobuf==3.20.0
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - six==1.16.0
    - tabulate==0.9.0
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-gpu==2.8.0
    - tensorflow-io-gcs-filesystem==0.34.0
    - termcolor==2.3.0
    - tf-estimator-nightly==2.8.0.dev2021122109
    - typing-extensions==4.8.0
    - urllib3==1.26.16
    - werkzeug==2.3.7
    - wrapt==1.15.0
    - zipp==3.17.0
